Add link to data browser + prefix in dataset overview page
NASA-IMPACT/veda-ui pull request #617
Opened 2023-08-14 16:39 UTC by slesaad

2023-08-16 22:34 UTC, slesaad commented
@danielfdsilva @hanbyul-here can you help make this better?

2023-08-22 13:56 UTC, danielfdsilva commented
After some internal discussion we agreed that adding another button to the dataset header is detrimental to the user experience. We recommend to use the "Analyse data" modal to link to external sources and/or having a direct link in the dataset page content.

We will set this up as an example and change the "analyse data" button label to better reflect the new modal nature. cc @hanbyul-here

2023-08-22 14:21 UTC, slesaad commented
@danielfdsilva @hanbyul-here let's hold this off for now, we showed a demo of this new feature, and it looks like we might need to make some changes. i think the external url will still hold, but how we do it might change.

2023-08-29 01:24 UTC, hanbyul-here commented
I went ahead and made the link to data browser as a part of 'Access Data' Modal. I updated this pr on veda ghg accordingly: https://github.com/NASA-IMPACT/veda-config-ghg/pull/41/files

2023-08-30 18:06 UTC, danielfdsilva approved these changes

2023-08-30 20:10 UTC, j08lue requested changes
Tiny typo

2023-08-30 20:11 UTC, j08lue approved these changes

2023-08-30 22:04 UTC, hanbyul-here commented on app/scripts/components/common/notebook-connect.tsx
> +      else if (d.url.match('browseui')) type = 'download';
(had a conversation with @slesaad and the answer is yes.

2023-08-30 22:04 UTC, merged