Set up trigger button and modal
NASA-IMPACT/veda-ui pull request #703
Opened 2023-10-17 12:48 UTC by nerik

2023-10-18 11:31 UTC, danielfdsilva requested changes
Maybe not part of this PR, but could be good to allow the user to clear all the AOIs by pressing the trash can with nothing selected.

2023-10-18 11:31 UTC, danielfdsilva commented on app/scripts/components/common/map/controls/aoi/custom-aoi-control.tsx
> +        />
The click listener should be on the button
```suggestion
      <SelectorButton onClick={() => setAoIModalRevealed(true)}>
        <CollecticonUpload2 title='Upload geoJSON' meaningful />
```

2023-10-19 11:44 UTC, merged

2023-10-19 11:48 UTC, nerik commented
@danielfdsilva Good suggestion. I don't see any other way to implement this (ie adding a custom listener on the trash button) than to rebuild the control from scratch, thoughts?

2023-10-19 12:02 UTC, danielfdsilva commented
Yeah... seems to be that way. I've rarely used the default controls. For the current analysis I had [created custom ones](https://github.com/NASA-IMPACT/veda-ui/blob/main/app/scripts/components/analysis/define/aoi-selector.tsx) and then [handled the events](https://github.com/NASA-IMPACT/veda-ui/blob/main/app/scripts/components/common/aoi/use-aoi-controls.ts) as I needed.

2023-10-19 12:03 UTC, danielfdsilva commented
There could be also an additional button to do that, maybe it is also clearer? like a reset?
The current analysis uses the arrows one:
<img width="617" alt="image" src="https://github.com/NASA-IMPACT/veda-ui/assets/1090606/aa878030-c78e-4d60-a3b2-fb3ae8c9b979">