Display error message when the analysis items is over max
NASA-IMPACT/veda-ui pull request #719
Opened 2023-10-31 10:17 UTC by danielfdsilva

<img width="1244" alt="Screenshot 2023-10-31 at 10 16 36" src="https://github.com/NASA-IMPACT/veda-ui/assets/1090606/09878bf5-5e6f-4ed8-abbe-eed9a01a1e72">

2023-10-31 12:53 UTC, j08lue requested changes
I have a suggestion for the error message to be a bit more gentle, perhaps. 😄 Would that work or does it get too long?

Either way - we will see, how users react to this and whether they understand how to change the range and repeat / continue the analysis in that case.

2023-10-31 12:53 UTC, j08lue commented on app/scripts/components/exploration/components/datasets/dataset-list-item-status.tsx
> +            Select a shorter time range.
```suggestion
            Please select a shorter time range.
```

2023-10-31 16:14 UTC, danielfdsilva commented
@j08lue Message updated!

2023-11-01 14:15 UTC, j08lue approved these changes

2023-11-02 09:14 UTC, merged