Guided tour of exploration page
NASA-IMPACT/veda-ui pull request #737
Opened 2023-11-07 17:46 UTC by danielfdsilva

I've been exploring user [react tour](https://docs.react.tours/) as a way to create a guided tour of the exploration page. I added a couple of steps just to show case how we could use it. There are a lot more to add, also after the user enter the "analysis mode.

@j08lue @ricardoduplos what do you think of this?

2023-11-08 09:35 UTC, j08lue requested changes
As I understood @ricardoduplos, it is a deliberate design choice to keep the controls very simple, without a lot of annotations and explaining labels. 👌 

I think in this case it is necessary to introduce essential features like the ones you highlighted with the guided tour here, @danielfdsilva.

The tour looks great, @danielfdsilva, and I agree with your choice of features to highlight. I am excited to see how our users respond to these.

I made some copy-editing suggestions on the texts - please review them and accept if you agree with my changes.

2023-11-08 09:35 UTC, j08lue commented on app/scripts/components/exploration/tour-manager.tsx
> +      "Each timeline entry represents a dataset, and each of the gray segments represents a data unit in the dataset. This data unit can be a day, month or year, depending on the dataset's time densi
```suggestion
      "Each row represents a dataset, and each of the boxes on the timeline represents a data unit in the dataset. This data unit can be a day, month or year, depending on the dataset's time density."
```

2023-11-08 09:35 UTC, j08lue commented on app/scripts/components/exploration/tour-manager.tsx
> +      'This is the main timeline playhead which can be used to select the date to view on the map. You can drag it around to change the date.'
```suggestion
      'Move this playhead to select a date to view on the map. You can drag it around or click on the timeline to place it.'
```

2023-11-08 09:35 UTC, j08lue commented on app/scripts/components/exploration/tour-manager.tsx
> +        Go ahead and try it out!
```suggestion
        You can zoom in on the timeline by scrolling while pressing the alt key (or
        option) and click and drag to pan.
        <br />
        Go ahead and try it out!
```

2023-11-08 09:35 UTC, j08lue commented on app/scripts/components/exploration/tour-manager.tsx
> +        selected datasets.
```suggestion
        You can calculate a time series (zonal statistics) for your area of interest (AOI). 
        Start that process here by drawing or uploading an AOI.
```

2023-11-09 16:54 UTC, danielfdsilva commented
@j08lue Added another tour when the user draws an AOI. Please give the messages some love :)

2023-11-10 14:05 UTC, j08lue requested changes
More copy editing for tour messages - I made some of them shorter and used the same type of phrase, presenting the opportunities ("you can ..."). 🤷

2023-11-10 14:05 UTC, j08lue commented on app/scripts/components/exploration/tour-manager.tsx
> +        statistics) for it.
```suggestion
        You can now calculate a time series of zonal
        statistics for your area of interest.
```

2023-11-10 14:05 UTC, j08lue commented on app/scripts/components/exploration/tour-manager.tsx
> +    title: 'Welcome to Exploration',
```suggestion
    title: 'Map layer selection',
```

2023-11-10 14:05 UTC, j08lue commented on app/scripts/components/exploration/tour-manager.tsx
> +        You can calculate a time series (zonal statistics) for your area of
```suggestion
        You can calculate a time series of zonal statistics for your area of
```

2023-11-10 14:34 UTC, merged