[#856] A&E Fast Follow Tweaks
NASA-IMPACT/veda-ui pull request #859
Opened 2024-02-26 21:04 UTC by sandrahoang686

This PR completes the following tasks in #856 

- [ ] select modal - update filter to remove redundant "Name" option
- [ ] card - remove link from collection title
- [ ] select modal - remove link from collection title on top of the modal
- [ ] info modal - change button text to "Open in Data Catalog"

@faustoperez Removed the linking in the selector modal and data layer card for the collection title and made the font color `base-500`. (color themes [here](https://ui.ds.io/latest/?path=/docs/components-theme-provider--colors)). Let me know if this should change

2024-02-27 08:52 UTC, faustoperez requested changes
Looking good Sandra! 

OK removing link on the collections but I think we should keep the primary color instead of gray.

Didn't see the changes on the info modal (link on collection title, button reads "Learn more":

<img width="910" alt="image" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/d46e45c2-ed30-4264-b183-575cff18a632">

Thanks!

2024-02-27 14:42 UTC, sandrahoang686 commented
@faustoperez thanks for reviewing and yes weird... it looks like I didn't push up one of my changes which is why the button still read that. done ✅

2024-02-27 14:58 UTC, faustoperez reviewed
Hi! Thanks for considering my feedback 👍 
The button reads correctly but I'm still seeing the link on the info modal collection title. Very minor thing, other than that it's good to merge :)

<img width="470" alt="image" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/12766f15-a70a-43ad-9ce1-5dd44e4cd909">

2024-02-27 15:13 UTC, faustoperez approved these changes
Thanks Sandra!

2024-02-27 15:17 UTC, merged

2024-02-28 11:12 UTC, j08lue commented
We missed a little detail, pls: https://github.com/NASA-IMPACT/veda-ui/issues/861

2024-02-28 14:56 UTC, sandrahoang686 commented
> Let us fix this little detail, pls: #861

@j08lue did you mean to post this comment on the ticket instead [here](https://github.com/orgs/NASA-IMPACT/projects/17/views/6?pane=issue&itemId=54605743)? I'll link it to the ticket and will work on it 👍🏼