[#846] Add analysis metrics menu to chart
NASA-IMPACT/veda-ui pull request #860
Opened 2024-02-27 19:30 UTC by sandrahoang686

This PR adds the analysis metrics menu back to each layer list item in the explorations page. 

Ticket [here](https://github.com/NASA-IMPACT/veda-ui/issues/856)

2024-02-28 09:46 UTC, faustoperez requested changes
Hi Sandra, I love the videos! Good call moving the icon to the right so it doesn't overlap the chart.

Could you please move it together with the units a little bit to the left (say 4-8px) so it has a bit of space? It's a little bit too tight now. Thanks!

<img width="133" alt="image" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/52ae82d6-27c0-4893-bd04-fbac816f53fe">

2024-02-28 09:50 UTC, faustoperez commented
As a side note related to this PR @j08lue @sandrahoang686 we need to review the behavior of the interface after triggering an analysis. I suggest:

- Fly and zoom the map to AOI
- Zoom the timeline to focus on the selected analysis period

I suggest we tackle that on #857

2024-02-29 13:49 UTC, j08lue approved these changes
Metrics selection works well with the new menu. I am not sure how well it can be found or we should use an icon that hints more at that these are chart-related options, now that the icon is not floating above the lines it is related to, but we can see in user testing, whether that is an issue and address it together with other planned design changes, if need be.

2024-02-29 14:31 UTC, faustoperez approved these changes
It's ok for now, might review the design at a later stage 👍 Thanks Sandra!

2024-02-29 14:32 UTC, merged