872 anlysis preset
NASA-IMPACT/veda-ui pull request #921
Opened 2024-04-18 12:46 UTC by hanbyul-here

**Related Ticket:** #872 

### Description of Changes
Add Analysis presets

### Notes & Questions About Changes

### Validation / Testing

2024-04-22 08:05 UTC, j08lue requested changes
Region selection works nicely!

I'll defer to @faustoperez for design review. I would recommend to change the region drop-down box title to an action that applies to the whole set of actions (e.g. "Analyze an area"), since it is currently the only title we have on that group of controls. What do you think?

The list of federal states should be ordered alphabetically, please.

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/2a34d9ea-bffb-4ba5-8638-3b931bb7c433)

Regarding the choice of geometries:
1. Level of detail - which geometries did you use, @hanbyul-here? [TIGER or cartographic](https://www.census.gov/programs-surveys/geography/guidance/tiger-data-products-guide.html)? I think the coarse cartographic ones (1:20 million) should be fine, but let me confirm that. We need to document our choice, not sure where - VEDA UI docs? Or a README in the `geo-data/states` dir?
2. All-US vs only [contiguous US](https://en.wikipedia.org/wiki/Contiguous_United_States) - I'll ask the GHG Center team but expect that we will need "United States (Contiguous)" as a second option to the full US. I cannot find a CONUS geometry on the CB website, though, so we might have to create it ourselves.

2024-04-22 08:25 UTC, hanbyul-here commented on app/scripts/components/common/map/controls/aoi/preset-selector.tsx
> +        <option> Select an area to analyze</option>
I included this change in https://github.com/NASA-IMPACT/veda-ui/pull/921/commits/7571a64d3a4557407d85b142c9a6fd3579287c71

2024-04-22 08:40 UTC, hanbyul-here commented
@j08lue I used the data from https://www.census.gov/cgi-bin/geo/shapefiles/index.php , with States (and equivalents) option. I think it is TIGER data as it is? Now that I see the options, cartographic would make more sense since the page simplifies the polygons anyway:  (https://github.com/NASA-IMPACT/veda-ui/pull/921/files#diff-c8fc4c13457e9e8ec776bfe2e55dc30a78b9e6c9f52d7a2c7094a4f7e5269c40R57)  To be clear, my question is not about the data resolution - it is about if the page is showing the states that people are expecting to see. ex. Do all the U.S. territories need to be included?

2024-04-22 10:23 UTC, j08lue commented
> the website already simplifies the polygons

Right, that may be something we need to communicate to users, because when users select a state, they may expect that it it follows the official definitions.

Btw, analysis requests for more complex states currently fail in the preview - e.g. Colorado works but [Arizona fails](https://deploy-preview-921--veda-ui.netlify.app/exploration?datasets=%5B%7B%22id%22%3A%22casa-gfed-co2-flux%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%2C%7B%22id%22%3A%22std%22%2C%22label%22%3A%22St+Deviation%22%2C%22chartLabel%22%3A%22St+Deviation%22%2C%22themeColor%22%3A%22infographicD%22%7D%2C%7B%22id%22%3A%22max%22%2C%22label%22%3A%22Max%22%2C%22chartLabel%22%3A%22Max%22%2C%22themeColor%22%3A%22infographicC%22%2C%22style%22%3A%7B%22strokeDasharray%22%3A%222+2%22%7D%7D%2C%7B%22id%22%3A%22min%22%2C%22label%22%3A%22Min%22%2C%22chartLabel%22%3A%22Min%22%2C%22themeColor%22%3A%22infographicA%22%2C%22style%22%3A%7B%22strokeDasharray%22%3A%222+2%22%7D%7D%5D%7D%7D%5D&date=2017-09-26T22%3A00%3A00.000Z&aois=%5B%22x%7E%7DbTycz%60Fmzq%40%7BBq_Chd%40ueuGgGhItqxH%7DHbwuBd%5C%5CrlaTdji%40%7BHfwlDg%40nkrDdJ%7EtpBokc%40dnpB_ub%40hz%7CAq%7E%5BdftAw%7BX%60s%60B%7Bu%5DzksA%7BcYl%7ClC%7D%60j%40%7DEgh%40vVym%40or%40uB%7D%5C%5CoMuEwLpDkRnj%40kJv%40_UrPeTmdAmeAg%40ySlPaLxDy%5DydAu%5EgQo%5C%5ClB_nAvEuA%7C%5Dn_%40bt%40x%5Ej%5Bn%40bQaSiEoh%40wu%40_ZcN_QmBkNhOkYsUib%40%7DCs%5C%5CrKsa%40pe%40kYhFu%60B%7BHeSkm%40eUgu%40pSmu%40_Oo%40i%5EeLqR_bBu_AuEwKbFs%5EalA%7Bv%40gVu%5ByUqzAunA%7DiByJmu%40cr%40%7D%7E%40ej%40w_BikAi%7EA%7DS%40efAvn%40uxLhx%40%7BR%7De%40ihEuAKam%40%7DiBHc%40ol%40u%7CCs%40Ysk%40igA%5BbDwz%40pXe_AwCexAwKyYon%40we%40chAq%7BA%7BcBci%40i%7CCugCae%40wgKnHm_%40dkAs%60AvYanAklAgmB%7DFaf%40%7CEcaAxH_P%7E%60%40qIjwAj%60%40hTgKzi%40ygEnf%40ypAr_%40kg%40nkA%7Bm%40lkHkb%40fm%40jJtb%40%60h%40j%5EnKdeAbDbnBeJjz%40aWjeA_xAdg%40qUzQjLdv%40zoA%60%5BdF%7Es%40e%60%40zPoW%60Hci%40cDit%40jnAguAhLe_%40Sop%40dlBwXxG%7Dx%40kYceBii%40mkBmz%40%7BbAsm%40wiB%7CDq%7D%40qa%40seBdTgoB__%40%7DyBlbBupCa%7DAix%40_NcQz%5D%7DgAvTiTbvAwe%40biD_l%40tz%40q_BgGwSgf%40wf%40maBaeAij%40qtAeQm_BlEmu%40xr%40w_B%5Boa%40niBeqBlE%7D%5BwZsOavBeCyZ%7DQoIgVeo%40oPcxAuF_iBtf%40%7Dk%40cD_f%40oRktAefA_m%40kxB%7EBgw%40i%60AywAkbAmaAk%7E%40woBgdA%7Dj%40kcAePqt%40_n%40%7BKg%7DAkuEq%7EBbkAatBnTky%40rAo_A%7Dz%40suAqx%40kq%40bx%40adARaZm%5C%5CsMaOwZ%7CHid%40zo%40qo%40CcSiOoPokAeHsV_LcBqL%60R%7BOhy%40gE%7CVkQpJ_QwBy%60%40iF%7BX%7Df%40mh%40ujD%7BcAiM%7BcAvMgeAbe%40%7B%60%40nHwT%60r%40me%40ep%40%7DgBfAqx%40hiA%7BnD%7CJmq%40xy%40%7BrBk%60%40cXcP_g%40d%7B%40wlCv%40kz%40%7Da%40aOc%7B%40hHmw%40gb%40kOgVzCmq%40puBefBjRus%40_kA%60Rg%5EwOoB_Z%7ESie%40ho%40ck%40fe%40wX%7Cz%40mThB%7Dv%40oi%40iqAed%40cl%40%7Di%40eRif%40hD_%7D%40u%5C%5CkxAwoAoZei%40i%7C%40wf%40iPiZ%7Dw%40kMuFiNdF%7BPxq%40i_%40_Hgc%40yN%7DFit%40%60Gw%5B_I%7Df%40qUua%40eg%40wSy%7DAlZu%7CBe%5EyqDgrBccC%7DaA%7BVozArG%7BeA%7Dc%40knAeOge%40g%5EeXyi%40_%5C%5C%7BRs%60BsAy%7EAy%5Bqt%40ke%40gxBehCgc%40qWmgAeHeg%40tJuoA%7BP%7BgAgf%40eV%7DVwcAcVwOcKaLm%5Ep%40%7B%7B%40%7DrAkp%40oaCwwBymA%7Dv%40%7DUym%40kq%40uMuOcVzCuf%40seAxGqt%40iGiy%40xIuLqBaKqSj%60%40%7DmA%7BBig%40zSkwA%7DEsr%40huBmzAngAifClp%40_%7B%40fmCskAhxAyEblAsTjUuQr%5Bmo%40x%7BByzA%7E%7D%40k%7D%40taBkJlt%40uTpQkYvBii%40hOsV%7Cb%40q%5EzgAif%40vuAg%5Bj%5Biq%40j%5C%5Cs%5C%5Cfl%40wGb%7DDn%5BltA%7DcA%60BuX_a%40ouApBi%7CBgYcfARux%40jOoqAlwCoxFvgBsbAnyAk%7CAUwG%7BcAgXcFa%7B%40tzAeiAxNap%40%7DEmq%40%7CK%7Dc%40%7Ck%40ml%40ts%40qb%40_D_Q%7D%5EyUwH_StVmZvL%7Bn%40tu%40%7DkAt_%40a%7DB%7EReOfu%40qBd_%40cLd%5Buw%40vxCadAxtAmzApjCy_Bhd%40sj%40flAw%7EB%7E%60%40ibC%60%7E%40e%7BBdwAekAppCklAdg%40cf%40v%5C%5Cmv%40%7CH_xAoc%40mpBxMyfB%7BTq%7BAJie%40b_%40ewAx%40%7De%40ae%40o%60CxEyu%40ti%40iaBxAggBsv%40qbBahCwbBoVgy%40hJah%40ls%40ur%40ty%40_b%40%7C%7DBwo%40pWq%60%40iy%40kaAgw%40ig%40o%7C%40kO_aCc%40uoAqTkh%40sUkb%40ebA%7EFec%40uZumBe%40g%7EBfO%7BgBnOyc%40l%5EsPzC%7DdAnRg%7B%40uB_w%40pR%7B%7C%40%7CBeuA%7E%7D%40ahEaF%7DfEtv%40woDdi%40q%7EApg%40q%7D%40%7CRsgBtc%40ynAf%7DCa_CxL_i%40xt%40_%7B%40fGuy%40%7EOwUaGmm%40%7Cm%40kp%40yFol%40v%5B%7Dk%40q%40%7BVzMi%5BwPcnBwe%40i%60%40cb%40%7BGqd%40ur%40oFi%5Bh%5C%5C%7Bw%40nGqyB%60Iw%5C%5CvW%7Bc%40%7El%40a_%40_%60%40aWkbAiVec%40qfAiA%7BdA%60d%40w%7C%40bl%40_UhcA%7BsBdiA_%7B%40pCeuAip%40enAqI%7Be%40tKg%5BftBemAbY%7Dk%40ko%40eqCcHucAhG_s%40sTkb%40fi%40qpAuI_aClnAa%7DA%7BOe%5Bic%40_%5Dor%40qdBnbAk%7BAk%40_%5C%5CwW%7DOan%40wFah%40ef%40epBeZiq%40ea%40%7EEiOxx%40k%5Dnj%40ym%40xiBmcAaFaFjqAclAvEcj%40eJuFf%40y%7C%40z%5DmW%7CgB%7BiDcC_OdiAcuApRsy%40sYgg%40lUyiBsYch%40m%7B%40%7De%40%7Bi%40%7Bh%40bHmS%60v%40we%40zu%40yBrF%7Bn%40gm%40su%40f%40yLrr%40%7DxAl%60%40sWbb%40%7DdAo%60%40ou%40e%7DAc%7C%40%7D%60E%7BVwy%40%7DWilAtRyy%40mh%40an%40cAev%40y%7C%40e_B%7Bv%40%7DYoEk%60%40yd%40eTbHog%40fw%40e_%40dLsc%40eN_qAcz%40oaByZc%7B%40%7D%5E_%7D%40b%40i%5EuHkm%40%60Jmz%40sE%7Bq%40vXe%7BBkQoRlDcp%40ng%40fDxRlXjKjXd%5DsCzSoV%7EOsc%40rB%7B%7CAmRw%7DAix%40%7Dd%40uCee%40%60Ig_%40fr%40if%40%7EZahC_jAcp%40qo%40e%7B%40sJkpCz%60%40%7Bt%40oLgUzEaeAr%7BAuuAvx%40m%60ArhAcv%40xP%7B%5Dtm%40avAhvA_O%7Cs%40fq%40jp%40%7CJrXsCpQa%5E%7CKu%7D%40w%40gaAdr%40es%40pQ%7Bu%40rBeMp%60AiYnk%40g_C%7EmAc%60AdNo%5DuI%7DfBw%40m%60Cm_%40kfBqh%40c_Ac%40mpAfVga%40sXwF_k%40gn%40kYeMs%60%40pGoy%40sPws%40qy%40yuAiZc_A%7Dl%40mr%40oAeJtSgXjc%40aXa%40oj%40wMaRg%7E%40y_%40efAmIa%60%40_fBm%60AuoA_Ncl%40ejAkfC%7Bq%40uu%40_%7BAma%40bIysQmHarDmF_xXdk%40exq%40hCqww%40gluP%7BC%22%2C%2249620%22%2Ctrue%5D&dateRange=2017-07-26T22%3A00%3A00.000Z%7C2017-11-26T23%3A00%3A00.000Z).

e.g. a request to https://ghg.center/api/stac/search with this payload:

```json
{"filter-lang":"cql2-json","limit":10000,"fields":{"include":["assets.npp.href","properties.start_datetime","properties.datetime"],"exclude":["collection","links"]},"filter":{"op":"and","args":[{"op":"t_intersects","args":[{"property":"datetime"},{"interval":["2017-07-27T00:00:00.000Z","2017-11-27T23:59:59.999Z"]}]},{"op":"s_intersects","args":[{"property":"geometry"},{"type":"MultiPolygon","coordinates":[[[[-114.81624,32.50811],[-114.81244,32.50062],[-114.81355,32.49402],[-114.08692,32.27355],[-113.65478,32.13965],[-113.15493,31.98239],[-112.71858,31.84979],[-112.23805,31.70138],[-111.65706,31.51866],[-111.07498,31.33234],[-110.1565,31.33413],[-109.26686,31.33393],[-109.05003,31.33235],[-109.04536,34.78541],[-109.04695,35.39343],[-109.0453,36.99898],[-110.46973,36.99766],[-110.4903,37.00363],[-110.75069,37.00301],[-111.15058,37.00095],[-114.05062,37.00017],[-114.04993,36.70952],[-114.04286,36.44949],[-114.04405,36.31749],[-114.04556,36.28884],[-114.04394,36.19335],[-114.05866,36.18784],[-114.0668,36.17909],[-114.07883,36.15743],[-114.08123,36.15021],[-114.0917,36.1373],[-114.09699,36.12082],[-114.10838,36.11915],[-114.1185,36.1139],[-114.12086,36.11085],[-114.12103,36.10389],[-114.11521,36.09988],[-114.1119,36.09584],[-114.1123,36.09405],[-114.11965,36.08582],[-114.12402,36.07556],[-114.13339,36.06167],[-114.13621,36.05323],[-114.13484,36.04387],[-114.13711,36.03849],[-114.14467,36.03427],[-114.14591,36.02723],[-114.15139,36.02313],[-114.16442,36.02685],[-114.17468,36.02667],[-114.19122,36.02002],[-114.21193,36.01483],[-114.22856,36.01455],[-114.23344,36.01284],[-114.24386,36.01527],[-114.26438,36.02791],[-114.26859,36.03503],[-114.27086,36.04552],[-114.27964,36.0461],[-114.28799,36.04907],[-114.29859,36.05726],[-114.30862,36.05698],[-114.31359,36.05905],[-114.31433,36.06202],[-114.31242,36.06612],[-114.30438,36.07402],[-114.30694,36.08249],[-114.32087,36.09646],[-114.32581,36.10393],[-114.33463,36.10678],[-114.3451,36.11856],[-114.35897,36.1278],[-114.37018,36.14262],[-114.37374,36.14372],[-114.38236,36.14156],[-114.40562,36.14698],[-114.41525,36.14512],[-114.42311,36.13735],[-114.44504,36.12535],[-114.45133,36.12983],[-114.45649,36.13803],[-114.4626,36.13964],[-114.46867,36.13889],[-114.48383,36.12972],[-114.49885,36 [...]

2024-04-22 12:32 UTC, hanbyul-here commented
Thanks for catching the issue @j08lue It seems each feature needs to be further simplified. I put an arbitrary value of 50 per each feature for now.

2024-04-23 21:06 UTC, sandrahoang686 approved these changes
wasn't able to be very thorough since I needed to focus on my ticket, given time constraint and at a quick glance, lgtm. 

Wasn't able to test manually but i'm guessing Jonas did

2024-04-23 21:22 UTC, j08lue commented
What are your plans for the geometries, @hanbyul-here?

I think the [response](https://developmentseed.slack.com/archives/C054MDFFCKV/p1713880024589489?thread_ts=1713781805.903769&cid=C054MDFFCKV) from @deborahUAH was that
1. States as ok as we have them now
2. CONUS for all US ("United States (Contiguous)") would be best but all-territories US is fine, too, if we cannot find a source for CONUS. Census.gov does not have one and I have been unable to find one elsewhere.

However, when the current United States feature gets simplified, the border to Canada is not aligned with the circle, which looks bad:

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/843b0bf8-63ed-482c-856a-866d3b36b900)

I think we need to at least find a way to make the default US outline look nicer. Maybe using the 1:20 million (cartographic) boundaries will work better, since they are pre-simplified more nicely? Or probably a CONUS one would look better, too? I can help produce that (by clipping the all-territories one), if need be.

2024-04-24 02:13 UTC, hanbyul-here commented
@j08lue So currently, I simplify each feature to have not more than 50 points, and I am not sure if this is enough points to generate the details of U.S. territory. So there are some options that we can try out.

1. Play with the data itself—as you said, the cartographic one will suit this purpose better. The current one on this branch is the one I just dissolved the states-equivalents (which is not ideal). But I am not sure that would be enough. 
2. Play with the maximum number of points per each feature—I couldn't figure out why the `/search` endpoint request with detailed polygon aoi failed. so it will be more try-out and see if this works. 

I am not sure if we can perfectly include only u.s.territory with the limitation of 2. I will try out 2, and I can replace the data to 1 : 20,000,000 (national)  cartographic one from this page: https://www.census.gov/geographies/mapping-files/time-series/geo/cartographic-boundary.html . If you find more suitable dataset, please feel free to try out. (`United Stastes.geojson` file https://github.com/NASA-IMPACT/veda-ui/pull/921/files#diff-af4e29cb69761c231c84c8fc4f5eb9d80b173c948d8b4f18c63863b5be61bfd1 need to be swapped out)

2024-04-24 03:41 UTC, hanbyul-here commented
I want to flag a but that I found while testing.
When I select 'Florida' with Fossil Fuel Co2Emissions, I get empty result: https://deploy-preview-339--ghg-demo.netlify.app/exploration?datasets=%5B%7B%22id%22%3A%22co2-emissions%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%5D&search=fuel&date=2021-11-30T15%3A00%3A00.000Z&aois=%5B%22rdgzNimiuCs_%40cqDaZkmAcbAoeCk%7B%40uvAejA%7DtAi_DwbCcbForCu_DcgA_qEuv%40c%7DC%7DOefDki%40gxCwUsdL%7BM_%60DjMs%7EEz%7B%40e%7BDt%7EAysAv%7B%40mdB%60%7CAguA%7EgBkdA%7CqB%7D%7B%40fyCwWroBcHdaB%5E%60qAnXhaDhmArgEzn%60%40Kbx%40dy%40xdAzi%40l%7DAx%5B%7Cs%40xCbpAgFrbAqS%60qBcy%40trBhe%40raAtD%60iByNfaAmZrdAop%40zmB%5DZj%7BSrvDwnAhxAev%40hdC%7DlBnmBm%60CrdA_rBl%7C%40iyCr%60%40qaE%22%2C%2251410%22%2Ctrue%2C%22d%7CkhNcyuyCznu%40nrkAhqsBno%7D%40%7EywAj%7BLb%7DC%60kN%7Eu%5DvnI%60kMorKxyDxrLblVt_Ehs%5Bi%7BWn%7ERraDf%7EG%7BxO%60uTDaqWgd%5Dgzz%40g%7ECggnA%7Bqf%40kc%7D%40hYljWuoYffHcxW%7BiBek_%40hqRcm%5Erm%5C%5CggYped%40ywAv%7BSucYjvXm%7DvAb__%40eXxp%5C%5CycTnhWgzfA%7EjxAq%7CjCnmA%7Dnf%40hqS_be%40gU%7B%7BfAsjV_rT%7BjJyni%40dxSi_kA%60%7E%5B%7CdBhkSqhHn%60%5Ea%7Dx%40pmb%40m%7EVtmGea%5C%5CddWqwNntMmo%5Bbnv%40wh%5C%5CfvQptBdfR%7E%7B%5C%5Cnf%5EndCf%7Cw%40%60%60e%40%60icA%7ErU%7C%7Ce%40uhPlyc%40c%7B%40vmQemU%7EcHkwc%40%60nVgeRtosBwlt%40jonA%7DtEpe%7CCbaV%40wv%5Do%7BK%7DjB%7EeI_tC_%7CYwvUlhOkmMarG%7Bf%5Ebqk%40shd%40c%7EE%7DsX_czNmWa%7BYhmw%40%7DqdOl%7DZx%7ECfaEogNddb%40ogWkwAaiEsmd%40%60yFec_%40ytQ%7DnRymaA%7CyTchr%40nTr%7EDzx_%40mjd%40jexCgru%40%60ewBe%7EiA%7CwgByrIfj%5BluMpid%40srGx_e%40gt_%40rv%7C%40%7DvdAttzDrgVruaG%22%2C%2251411%22%2Ctrue%5D&dateRange=2021-09-30T15%3A00%3A00.000Z%7C2021-12-31T15%3A00%3A00.000Z


But when I draw aoi roughly on top of Florida, the statistics return the results: https://deploy-preview-339--ghg-demo.netlify.app/exploration?datasets=%5B%7B%22id%22%3A%22co2-emissions%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%5D&search=fuel&date=2021-11-30T15%3A00%3A00.000Z&aois=%5B%22nf%60%7BNsfgwDgxdIeve%40_%7CbQnveXbfeUncoKjbgMmdsB%22%2C%22c40962%22%2Ctrue%5D&dateRange=2021-09-30T15%3A00%3A00.000Z%7C2021-12-31T15%3A00%3A00.000Z

As far as I can check, the response from endpoints are empty when `/statistics` request is made with detailed polygons.

2024-04-24 08:01 UTC, j08lue commented
Here is a CONUS geometry generated from the Census.gov `cb_2023_us_nation_20m` https://gist.github.com/j08lue/aaa068d76f56059544d02cb3141c9e72

An issue with the geometry is that it is cropped to land, so the boundary does not include some parts of e.g. Lake Superior that belong to the U.S., but I think we can live with that - and users will be able to see this when they add the region to the map:

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/a0c6d0a1-e04c-4801-bc33-d2f15669a75d)

I think we should use the 1:20 million "Cartographic" files, because we do not need greater level of detail than that anyways. I'll create a notebook that downloads and converts them to GeoJSON, so we can document and reproduce the process.

2024-04-24 08:09 UTC, hanbyul-here commented
Having a notebook to regenerate the files sounds good. I used a 1:20m cartographic one for state preset: https://github.com/NASA-IMPACT/veda-ui/pull/921/commits/7e6b38794868371043a0143da11fd961aa1d390b So the current presets are 1:20m cartographic one (and further simplified on the fly when needed).

2024-04-24 09:25 UTC, j08lue commented
Cool you were already using the 1:20m data. Here is a notebook which also generates the CONUS region: https://gist.github.com/j08lue/09aa6f68a8566afbbc9d3e80e8e7908a

Should we still replace the files with the ones the notebook generates, for consistency? And should we add the notebook to this repo somewhere, like under `docs/development`?

2024-04-24 12:57 UTC, j08lue commented
I added the script and the data it generates. This omits some of the island territories. I just use what the cartographic shapefile from Census.gov includes, as the newly added script shows: https://github.com/NASA-IMPACT/veda-ui/blob/19bf62da1ce62a6e916132edfd6ae26d393bc5c2/docs/development/geo-data-preparation.ipynb

2024-04-24 13:47 UTC, j08lue commented
The only geometries failing are Alaska and all-USA (which includes Alaska).

I do not think this is because of the complexity of the polygons but because of antimeridian crossing or so - when I select only Alaska mainland (no islands), the analysis works.

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/e5f77645-16e8-47a3-ad08-be6aa6c828ec)

I will merge this PR and open a ticket for fixing Alaska.

2024-04-24 13:47 UTC, j08lue approved these changes
Geometries are correct and analysis works fine for all regions except Alaska and all-US (including Alaska). We will track fixing that separately.

2024-04-24 13:48 UTC, merged

2024-04-25 11:00 UTC, hanbyul-here commented
For the record: 
Most of the weird behaviors I observed seem to be from polygons not getting properly combined into a multipolygon (to make a request, fixed by https://github.com/NASA-IMPACT/veda-ui/pull/921/commits/6de97b059024106ddfd3a60d612367e1cb0063b2) - This bug had persisted before this PR, this PR made the problem more visible.